version: '3.3'

services:
  postgres:
    image:  postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/initdb:/docker-entrypoint-initdb.d
      - psql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=phone
      - POSTGRES_USER=admin
      - POSTGRES_PWD=admin123

volumes:
  psql-data:
